### ISSUE TITLE
Getting this PHP Fatal error on w10, Pasted error log, any idea whats wrong?

### ISSUE THREAD

**Issue by vFrodo** [ManiaControl/ManiaControl#279]
[14-Apr-2022 20:05:56 UTC] Starting ManiaControl...
[14-Apr-2022 20:05:56 UTC] Checking for minimum required PHP-Version 5.4 ... 8.1.5 OK!
[14-Apr-2022 20:05:56 UTC] Checking for installed MySQLi ... FOUND!
[14-Apr-2022 20:05:56 UTC] Checking for installed cURL ... FOUND!
[14-Apr-2022 20:05:56 UTC] Checking for installed PHP ZIP ... FOUND!
[14-Apr-2022 20:05:56 UTC] Checking for installed Zlib ... FOUND!
[14-Apr-2022 20:05:56 UTC] Checking for installed mbstring ... FOUND!
[14-Apr-2022 20:05:56 UTC] Loading ManiaControl v0.256 ...
[14-Apr-2022 20:05:56 UTC] [PHP ERROR '8192']: Return type of cURL\RequestsQueue::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
File&Line: C:\Users\Thoma\Desktop\server controller\ManiaControl-master\libs\curl-easy\cURL\RequestsQueue.php: 134
Trace: 
#0: include_once(string(C:\Users\Thoma\Desktop\server controller..)) in File core\AutoLoader.php on Line 42
#1: ManiaControl\AutoLoader::autoload(string(cURL\RequestsQueue)) in File core\Files\AsynchronousFileReader.php on Line 42
#2: ManiaControl\Files\AsynchronousFileReader->__construct(object(ManiaControl\ManiaControl)) in File core\ManiaControl.php on Line 204
#3: ManiaControl\ManiaControl->__construct() in File ManiaControl.php on Line 55

[14-Apr-2022 20:05:56 UTC] PHP Fatal error:  During inheritance of Countable: Uncaught Error: Call to a member function addRequest() on null in C:\Users\Thoma\Desktop\server controller\ManiaControl-master\core\Files\AsyncHttpRequest.php:129
Stack trace:
#0 C:\Users\Thoma\Desktop\server controller\ManiaControl-master\core\Files\AsyncHttpRequest.php(81): ManiaControl\Files\AsyncHttpRequest->processRequest(Object(cURL\Request))
#1 C:\Users\Thoma\Desktop\server controller\ManiaControl-master\core\ErrorHandler.php(196): ManiaControl\Files\AsyncHttpRequest->getData()
#2 C:\Users\Thoma\Desktop\server controller\ManiaControl-master\libs\curl-easy\cURL\RequestsQueue.php(7): ManiaControl\ErrorHandler->handleError(8192, 'Return type of ...', 'C:\\Users\\Thoma\\...', 134)
#3 C:\Users\Thoma\Desktop\server controller\ManiaControl-master\core\AutoLoader.php(42): include_once('C:\\Users\\Thoma\\...')
#4 C:\Users\Thoma\Desktop\server controller\ManiaControl-master\core\Files\AsynchronousFileReader.php(42): ManiaControl\AutoLoader::autoload('cURL\\RequestsQu...')
#5 C:\Users\Thoma\Desktop\server controller\ManiaControl-master\core\ManiaControl.php(204): ManiaControl\Files\AsynchronousFileReader->__construct(Object(ManiaControl\ManiaControl))
#6 C:\Users\Thoma\Desktop\server controller\ManiaControl-master\ManiaControl.php(55): ManiaControl\ManiaControl->__construct()
#7 {main} in C:\Users\Thoma\Desktop\server controller\ManiaControl-master\libs\curl-easy\cURL\RequestsQueue.php on line 7
[14-Apr-2022 20:05:56 UTC] [PHP ERROR]: During inheritance of Countable: Uncaught Error: Call to a member function addRequest() on null in C:\Users\Thoma\Desktop\server controller\ManiaControl-master\core\Files\AsyncHttpRequest.php:129
Stack trace:
#0 C:\Users\Thoma\Desktop\server controller\ManiaControl-master\core\Files\AsyncHttpRequest.php(81): ManiaControl\Files\AsyncHttpRequest->processRequest(Object(cURL\Request))
#1 C:\Users\Thoma\Desktop\server controller\ManiaControl-master\core\ErrorHandler.php(196): ManiaControl\Files\AsyncHttpRequest->getData()
#2 C:\Users\Thoma\Desktop\server controller\ManiaControl-master\libs\curl-easy\cURL\RequestsQueue.php(7): ManiaControl\ErrorHandler->handleError(8192, 'Return type of ...', 'C:\\Users\\Thoma\\...', 134)
#3 C:\Users\Thoma\Desktop\server controller\ManiaControl-master\core\AutoLoader.php(42): include_once('C:\\Users\\Thoma\\...')
#4 C:\Users\Thoma\Desktop\server controller\ManiaControl-master\core\Files\AsynchronousFileReader.php(42): ManiaControl\AutoLoader::autoload('cURL\\RequestsQu...')
#5 C:\Users\Thoma\Desktop\server controller\ManiaControl-master\core\ManiaControl.php(204): ManiaControl\Files\AsynchronousFileReader->__construct(Object(ManiaControl\ManiaControl))
#6 C:\Users\Thoma\Desktop\server controller\ManiaControl-master\ManiaControl.php(55): ManiaControl\ManiaControl->__construct()
#7 {main}
File&Line: C:\Users\Thoma\Desktop\server controller\ManiaControl-master\libs\curl-easy\cURL\RequestsQueue.php: 7
[14-Apr-2022 20:05:57 UTC] Error-Report successful!
[14-Apr-2022 20:05:57 UTC] Quitting ManiaControl after Fatal Error.

**Comment by LikeAJohny** [comment]
I'd guess that you're running ManiaControl in a PHP 8 environment. Looks like either ManiaControl - curl in this instance - is not ready for PHP 8 yet.
Try running it on PHP7 instead.

All above is guessing as I haven't checked any ManiaControl files myself.
